In [67]:
#Project 2
# Bigmart Dataset

1. Extract and load the data
2. EDA
3. Data cleaning
4. Data preprocessing
5. divide set into input and output
6. Split data into train and test
7. Apply Algorithm
8. Predict Outcomes
9. Evaluate
10. Deploy

In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Extract and load the data

In [69]:
#load data
df=pd.read_csv('bigmart.csv',encoding='unicode_escape')
df

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [70]:
from plotly import express

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [72]:
df.shape

(8523, 12)

In [73]:
df.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [74]:
df.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [75]:
# 1. Display top 5 rows.

In [76]:
df.iloc[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [77]:
# 2. Display last 5 rows.

In [78]:
df.iloc[-5:]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [79]:
# 3. Display Random 5 rows.

In [80]:
df.sample(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
3573,FDR48,11.650,LF,0.131709,Baking Goods,152.3024,OUT049,1999,Medium,Tier 1,Supermarket Type1,1518.0240
7872,FDH16,10.500,Low Fat,0.052555,Frozen Foods,89.6830,OUT046,1997,Small,Tier 1,Supermarket Type1,988.7130
5876,FDW19,12.350,Regular,0.064442,Fruits and Vegetables,110.9570,OUT010,1998,NaN,Tier 3,Grocery Store,219.7140
6369,FDO08,11.100,Regular,0.054080,Fruits and Vegetables,165.9526,OUT017,2007,NaN,Tier 2,Supermarket Type1,2631.2416
2313,FDM13,6.425,Low Fat,0.105743,Breakfast,130.5626,OUT010,1998,NaN,Tier 3,Grocery Store,131.1626

In [81]:
# 4. Identify duplicate values if any.

In [82]:
df.duplicated().sum()

np.int64(0)

In [83]:
# 5. Identify Duplicate rows.

In [84]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [85]:
# 6. Identify number of unique values for each feature.

In [86]:
df.nunique()

Item_Identifier              1559
Item_Weight                   415
Item_Fat_Content                5
Item_Visibility              7880
Item_Type                      16
Item_MRP                     5938
Outlet_Identifier              10
Outlet_Establishment_Year       9
Outlet_Size                     3
Outlet_Location_Type            3
Outlet_Type                     4
Item_Outlet_Sales            3493
dtype: int64

In [87]:
# 7. Identify datatype of each feature.

In [88]:
df.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [89]:
# identify x missing values
df.isnull().sum()/df.shape[0]*100

Item_Identifier               0.000000
Item_Weight                  17.165317
Item_Fat_Content              0.000000
Item_Visibility               0.000000
Item_Type                     0.000000
Item_MRP                      0.000000
Outlet_Identifier             0.000000
Outlet_Establishment_Year     0.000000
Outlet_Size                  28.276428
Outlet_Location_Type          0.000000
Outlet_Type                   0.000000
Item_Outlet_Sales             0.000000
dtype: float64

In [90]:
#Apply the missing value treatement

In [91]:
df['Item_Weight'].fillna(df['Item_Weight'].mean(),inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_17768\3323749204.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [92]:
df['Item_Weight'].describe()

count    8523.000000
mean       12.857645
std         4.226124
min         4.555000
25%         9.310000
50%        12.857645
75%        16.000000
max        21.350000
Name: Item_Weight, dtype: float64

In [93]:
#df['Item_Weight'].fillna(12.85)

In [94]:
df.isnull().sum()/df.shape[0]*100

Item_Identifier               0.000000
Item_Weight                   0.000000
Item_Fat_Content              0.000000
Item_Visibility               0.000000
Item_Type                     0.000000
Item_MRP                      0.000000
Outlet_Identifier             0.000000
Outlet_Establishment_Year     0.000000
Outlet_Size                  28.276428
Outlet_Location_Type          0.000000
Outlet_Type                   0.000000
Item_Outlet_Sales             0.000000
dtype: float64

In [95]:
df['Outlet_Size'].value_counts()

Outlet_Size
Medium    2793
Small     2388
High       932
Name: count, dtype: int64

In [96]:
df['Outlet_Size']=df['Outlet_Size'].fillna(df['Outlet_Size'].mode()[0])

In [97]:
df.isnull().sum()/df.shape[0]*100

Item_Identifier              0.0
Item_Weight                  0.0
Item_Fat_Content             0.0
Item_Visibility              0.0
Item_Type                    0.0
Item_MRP                     0.0
Outlet_Identifier            0.0
Outlet_Establishment_Year    0.0
Outlet_Size                  0.0
Outlet_Location_Type         0.0
Outlet_Type                  0.0
Item_Outlet_Sales            0.0
dtype: float64

In [98]:
#identify continuous and categorical features

In [99]:
df.nunique()

Item_Identifier              1559
Item_Weight                   416
Item_Fat_Content                5
Item_Visibility              7880
Item_Type                      16
Item_MRP                     5938
Outlet_Identifier              10
Outlet_Establishment_Year       9
Outlet_Size                     3
Outlet_Location_Type            3
Outlet_Type                     4
Item_Outlet_Sales            3493
dtype: int64

In [100]:
cat=[]
cont=[]
for i in df.columns:
    if df[i].nunique()<16:
        cat.append(i)
    else:
        cont.append(i)
print("Categorical Features : ", cat)
print("Continuous Features : ", cont)

Categorical Features :  ['Item_Fat_Content', 'Outlet_Identifier', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']
Continuous Features :  ['Item_Identifier', 'Item_Weight', 'Item_Visibility', 'Item_Type', 'Item_MRP', 'Item_Outlet_Sales']

# EDA for categorical columns

In [101]:
#Univariate Analysis

In [102]:
df['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat    5089
Regular    2889
LF          316
reg         117
low fat     112
Name: count, dtype: int64

In [103]:
df.replace('LF','Low Fat',inplace=True)

In [104]:
df.replace('low fat','Low Fat',inplace=True)

In [105]:
df.replace('reg','Regular',inplace=True)

In [106]:
for i in cat:
    print(df[i].value_counts())
    print("-------------------------------------------")
    print( )

Item_Fat_Content
Low Fat    5517
Regular    3006
Name: count, dtype: int64
-------------------------------------------

Outlet_Identifier
OUT027    935
OUT013    932
OUT035    930
OUT049    930
OUT046    930
OUT045    929
OUT018    928
OUT017    926
OUT010    555
OUT019    528
Name: count, dtype: int64
-------------------------------------------

Outlet_Establishment_Year
1985    1463
1987     932
1999     930
1997     930
2004     930
2002     929
2009     928
2007     926
1998     555
Name: count, dtype: int64
-------------------------------------------

Outlet_Size
Medium    5203
Small     2388
High       932
Name: count, dtype: int64
-------------------------------------------

Outlet_Location_Type
Tier 3    3350
Tier 2    2785
Tier 1    2388
Name: count, dtype: int64
-------------------------------------------

Outlet_Type
Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: count, dtype: int64
-------------------------------------------

In [107]:
for i in cat:
    print(round(df[i].value_counts(normalize=True)*100,2))
    print("-------------------------------------------")
    print( )

Item_Fat_Content
Low Fat    64.73
Regular    35.27
Name: proportion, dtype: float64
-------------------------------------------

Outlet_Identifier
OUT027    10.97
OUT013    10.94
OUT035    10.91
OUT049    10.91
OUT046    10.91
OUT045    10.90
OUT018    10.89
OUT017    10.86
OUT010     6.51
OUT019     6.20
Name: proportion, dtype: float64
-------------------------------------------

Outlet_Establishment_Year
1985    17.17
1987    10.94
1999    10.91
1997    10.91
2004    10.91
2002    10.90
2009    10.89
2007    10.86
1998     6.51
Name: proportion, dtype: float64
-------------------------------------------

Outlet_Size
Medium    61.05
Small     28.02
High      10.94
Name: proportion, dtype: float64
-------------------------------------------

Outlet_Location_Type
Tier 3    39.31
Tier 2    32.68
Tier 1    28.02
Name: proportion, dtype: float64
-------------------------------------------

Outlet_Type
Supermarket Type1    65.43
Grocery Store        12.71
Supermarket Type3    10.97
Supermarket Type2    10.89
Name: proportion, dtype: float64
-------------------------------------------

In [108]:
# univariate Analysis
#visualization
e= express.bar(df['Item_Fat_Content'].value_counts() )
e.show()

In [109]:
for i in cat : 
    e = express.bar(df[i].value_counts()  )   
    e.show()

# EDA for Continuous columns

In [110]:
df[cont].describe().round(2)

       Item_Weight  Item_Visibility  Item_MRP  Item_Outlet_Sales
count      8523.00          8523.00   8523.00            8523.00
mean         12.86             0.07    140.99            2181.29
std           4.23             0.05     62.28            1706.50
min           4.56             0.00     31.29              33.29
25%           9.31             0.03     93.83             834.25
50%          12.86             0.05    143.01            1794.33
75%          16.00             0.09    185.64            3101.30
max          21.35             0.33    266.89           13086.96

# Preprocessing

Categorical:

In [112]:
df_cat=df[cat].drop('Outlet_Establishment_Year',axis=1)

In [113]:
df_cat_dummies=pd.get_dummies(df_cat,dtype=int)

In [114]:
df_cat_dummies.shape

(8523, 22)

Numerical:

In [115]:
df['Item_Identifier'].nunique()

1559

In [116]:
df_num=df[cont].drop(['Item_Identifier','Item_Outlet_Sales'],axis=1)

In [117]:
# Apply Min Max Scaler

In [118]:
from sklearn.preprocessing import MinMaxScaler

In [119]:
MM=MinMaxScaler()

In [120]:
df_num=df_num.drop('Item_Type',axis=1)

In [121]:
df_num_mm=MM.fit_transform(df_num)

In [122]:
df_num_df=pd.DataFrame(df_num_mm,columns=df_num.columns)

In [123]:
df_final=pd.concat([df_num_df,df_cat_dummies],axis=1)

In [124]:
df_final

,Item_Weight,Item_Visibility,Item_MRP,Item_Fat_Content_Low Fat,Item_Fat_Content_Regular,Outlet_Identifier_OUT010,Outlet_Identifier_OUT013,Outlet_Identifier_OUT017,Outlet_Identifier_OUT018,Outlet_Identifier_OUT019,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,0.282525,0.048866,0.927507,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,0.081274,0.058705,0.072068,0,1,0,0,0,1,0,...,0,1,0,0,0,1,0,0,1,0
2,0.770765,0.051037,0.468288,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,0.871986,0.000000,0.640093,0,1,1,0,0,0,0,...,0,1,0,0,0,1,1,0,0,0
4,0.260494,0.000000,0.095805,1,0,0,1,0,0,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,0.137541,0.172914,0.777729,1,0,0,1,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8519,0.227746,0.143069,0.326263,0,1,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
8520,0.359929,0.107148,0.228492,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8521,0.158083,0.442219,0.304939,0,1,0,0,0,1,0,...,0,1,0,0,0,1,0,0,1,0
8522,0.610003,0.136661,0.187510,1,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0

In [125]:
df_final.shape

(8523, 25)

# 5. Decide I/p and O/p

In [126]:
X=df_final 
Y=df['Item_Outlet_Sales']

# 6. Train test Split

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.10,random_state=123)

In [131]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((7670, 25), (853, 25), (7670,), (853,))

In [132]:
from sklearn.linear_model import LinearRegression

In [133]:
LR=LinearRegression()

In [134]:
LR.fit(X_train,Y_train)

LinearRegression()

In [135]:
LR.coef_

array([  -21.3358576 ,   -60.96595619,  3671.44603587,   -23.92199889,
          23.92199889,  -686.66932279,   -14.70341441,    10.31051569,
         -51.33668601,  -375.46412466,   820.35595907,   174.90911924,
        -154.3739081 ,   151.54156468,   125.43029729,   -14.70341441,
          63.71685515,   -49.01344074,   -98.49226269,    30.84572683,
          67.64653586, -1062.13344745,   293.11417439,   -51.33668601,
         820.35595907])

In [136]:
LR.intercept_

np.float64(280.5859702239461)

In [137]:
pred=LR.predict(X_test)

In [138]:
pred

array([  890.75196477,   786.77456762,  3096.29252759,  1806.49415256,
        3977.31594189,   533.2572536 ,  2875.30484808,  2777.36543741,
         883.77209416,  2505.65849012,  3905.74636273,  2772.62407106,
        2706.84081713,  1221.80418403,  2845.96602702,   934.2940957 ,
        1734.9170636 ,  1127.24017375,  2306.896672  ,  3572.09350681,
         606.91345036,   841.62281273,  1507.8667016 ,  3117.92644151,
        2900.42259634,  4046.16523742,  2469.16419183,  2018.2490985 ,
        4206.92773902,  3718.72070762,   844.8865818 ,  1919.40241481,
         112.5655122 ,  1866.85254474,  -315.87238202,  2430.67404903,
        2490.04967779,  1910.22281296,  3292.74778979,   937.36292124,
        3727.99619412,  2177.49659057,  1088.23091951,  5409.22017186,
        1393.71176962,  2635.5773858 ,  1215.84632707,  1777.8610742 ,
         948.8897359 ,  -252.086278  ,  2749.23784896,   883.98187075,
        4210.77441925,  3225.28256923,  2768.91895983,  3847.33005163,
        2645.43534734,  1366.67841222,  2007.63282534,  2945.29527693,
        2837.86175714,  3414.15389317,  1384.65881022,  4243.10063188,
        3610.80027019,  2731.32823236,  2742.91956504,  5510.63226412,
        4177.55235795,  2505.64732388,  4280.56690489,   869.71303913,
        1969.14908419,  1715.79958405,  3841.87482047,   765.1129237 ,
         806.87883864,  3057.99395268,  3845.54925332,   791.69151312,
        4671.41169663,  5564.75690108,  4237.7999892 ,  3439.36712615,
        2965.47170858,  2106.56357163,  1302.23806968,  2489.69528291,
        3587.69730036,  3509.58859373,  2333.79483159,  1176.15015847,
         679.42596185,   154.72100274,  2177.50175124, -1059.24168891,
        2431.11977285,  2091.91168137,  1953.28675206,   989.37991134,
        2958.78720277,  2203.89083708,  3584.53901488,  3510.8871648 ,
        1928.79249546,   -40.26656268,  2320.12748052,  3803.52266146,
        1670.36912744,  1924.31311565,  3490.75330074,  1615.7815188 ,
          66.87932405,  2558.1660852 ,  -530.21136126,  1101.4979864 ,
        1985.37374024,  4525.02521237,  3729.93601578,  3896.71469584,
        3436.38441455,  2064.70344323,  -473.52983656,   -46.5756727 ,
        3173.94638916,  2967.65327314,  2168.29314375,  2800.92033563,
        1819.6306628 ,  2915.25458288,   567.9796728 ,   916.65572424,
        3726.55593362,  1470.19859122,  2366.23581842,  1486.88305281,
        3461.83852353,  3930.4514903 ,  3953.91210102,   644.00406182,
        2441.2237471 ,  2751.69523792,  3619.74087404,  1469.95096745,
        3728.6649735 ,   -48.47753642,  2819.39578873,  4203.38312042,
        5494.10588731,  2822.16620862,  4269.5113987 ,  2355.77313112,
        1801.80464429,   926.28212138,  1635.71034778,  2897.98837129,
        3254.92781798,  1803.73697062,  2718.57121622,   748.43757009,
        3369.9503189 ,  3450.409302  ,   950.19984839,  1772.13415971,
        1596.27435409,  1132.56475421,  3050.86201448,  2443.63034272,
        3755.55288151,   562.56918119,  2182.9434185 ,  2421.59902478,
        2834.42173537,  1804.63376794,  2738.26886952,  1666.29819182,
        3308.80691655,  5302.55136299,  2893.40657613,  1661.76647694,
        3368.95588503,  4087.68141597,  1700.08221517,  1283.40061183,
        -210.91040725,  1813.55096872,  2471.13147334,  3642.66399268,
        -460.45762134,    85.81686532,  2130.17201317,  1676.38527753,
        2194.83249793,  2949.81593156,  -630.22426627,  3195.41775512,
        1710.93836818,  1691.67173815,   614.49212885,  1952.94248866,
         735.64364288,  4141.06566388,  3969.27155049,  3640.66309499,
        1534.72682228,  1569.23387929,  3016.52247533,   351.12746421,
         813.099574  ,  2384.8036234 ,  5504.05556493,  1615.42353361,
        2224.03054832,   818.16575024,  2159.1298233 ,  1691.98600926,
        2012.36682886,  1779.37888309,  3156.95712417,  2818.30785724,
        2897.78079134,  3088.18601131,  1437.13385916,  3543.87548246,
        1854.16728953,  2098.20713506,  2275.71972398,  2938.71667524,
        4128.71013795,  1773.79580595,  1863.84437583,  2060.80658991,
        3736.59123039,  2059.0151677 ,  2072.26333142,  1154.22126932,
        1149.19204212,  2813.85969796,   911.09990865,  2001.16903402,
        2540.29162809,  2463.64118873,  4158.8491035 ,    47.85043435,
        4143.29292403,  4139.98045116,  4276.29931728,  2140.64605199,
         631.12532281,  2340.03476007,  2729.17384203,  3506.00803667,
        2169.96445794,  3042.87875121,  2587.92576212,  1389.21448157,
        2133.68487206,  2973.16358834,  2048.58249838,   513.22913839,
        -384.18045913,   746.17683921,  2391.62548273,  2220.12719066,
        1366.028158  ,   924.62427247,  3562.79922966,  2448.24351516,
        2451.79100133,  2032.05407775,  2614.9185206 , -1246.70047046,
         966.51078912,  1910.2448489 ,  2063.16846656,   758.76081633,
        2633.68945746,  1706.23958665,  1767.47702183,  1638.3611822 ,
        2823.01391506,  1689.98779401,  2918.71317652,  3231.06751121,
        3392.91030072,  3050.01297806,   -56.08470828,  3037.85568275,
        2957.30037364,  2502.6152871 ,  2955.42552409,   836.19765558,
         930.64295038,  -536.76672938,  1765.28600969,  1424.3410974 ,
        4250.8056834 ,   930.97350722,  3043.6021506 ,  2613.93261329,
        2134.23396927,  3868.13284359,  3060.4575763 ,  2963.14330943,
        2444.38490494, -1257.39640994,  1044.69635825,  3435.45441353,
         388.28119262,  4592.91196936,  1892.26086214,  3149.0663993 ,
         880.62360799,  2524.0980788 ,   610.43194413,  3152.27666474,
        2220.51995679,  4580.9348049 ,   314.61693253,  1179.20600908,
        2858.75001832,  1237.99065939,  3924.76537869,  2336.72837842,
         955.45725491,  2603.51542146,  3264.50787804,  1953.39543353,
        4051.58384704,   612.17188055,  2605.56521937,  1268.505922  ,
        1742.76523528,  1489.88128784,  2784.05294458,  1838.6717349 ,
         761.61923788,  1360.96010326,  1042.5327201 ,  2801.99336585,
        3995.07571011,  4586.82084596,  2941.90996247,  4346.82182328,
        2508.86398913,    21.52377194,   435.62936431,  1687.39118508,
        1605.14219728,  2966.90507256,  2075.83502172,  1269.55672298,
        3744.14616499,  1955.63403506,  3918.11106783,  4166.46664676,
        2848.70981559,  3385.39949083,  2754.09154036,  1007.27505618,
        2089.6084713 ,  4093.74951346,  3113.228422  ,  1414.25568315,
        1396.18404194,  3129.08505109,  1631.95181942,  -407.2402253 ,
        -238.09422091,  1579.19509432,  2292.589966  ,  2444.37202481,
        1879.98928683,  3993.26323036,  3094.51915927,  2788.6384007 ,
        4027.6070631 ,   817.45455501,  1739.68131454,  4526.25601601,
        1905.14904678,  2758.79425603,   790.50118715,  2132.63760258,
        1677.84074719,  2557.27321323,  1009.14114579,  1951.22001612,
        3785.55331086,   517.54504887,  1244.20240814,  3274.92909541,
        1988.08767169,  1658.07513279,  3105.09852496,  1167.2116676 ,
        4228.27467161,  2493.45757578,   722.18744889,  2455.27038677,
        3946.26176816,  2523.34637668,  1412.26909277,   877.67189034,
        2772.94488991,   615.96708143, -1206.90121472,  3585.49470395,
        1509.19804567,  3760.11424114,  2832.84427006,   437.97945163,
        1523.81300794,  1815.59905712,   -27.70816138,  3957.04443252,
        2947.83485487,   747.46673997,  2348.56265163,  1951.86393272,
        1603.62931115,  2668.37863853,  3412.77916883,  1378.26494452,
         -32.97231726,  3882.73166634,  -232.58254746,   972.62365312,
         968.52308215,  2790.77594317,   549.4649061 ,  3241.0452157 ,
        1135.8011677 ,   730.42050949,  3493.74916532,  2246.6979049 ,
        1220.92683924,  -399.34207393,  2489.93938148,  3383.5629771 ,
        2424.96582947,  2925.38476475,  4129.06201497,  2529.54363941,
        3474.98762064,   907.24957293,   603.86179201,   730.71470398,
        1882.27995733,   719.47564562,  -942.57396708,  4068.42358279,
         166.61683977,  1860.43624387,  1352.88535773,  1813.40037713,
        2102.77793725,   984.40500999,   768.07683496,  2362.08858923,
        4078.04414147,  1315.23013175,  2883.2326432 ,  1411.59504766,
        3034.73254181,  1690.43661875,  3303.86651016,  4397.06272352,
        2465.12389541,  3302.51419176,  1868.95408628,   712.00145097,
        1746.10373367,  2051.85450574,  1684.53058445,   683.15450618,
        3740.59877824,  2326.98591394,  1663.26227419,  3156.90080952,
        1471.33731546,  2900.40719407,  2053.34695891,  1420.58057043,
        1032.86046122,  2303.80883639,  1159.84695845,    16.40881625,
        3231.68180071,  2314.07265218,  1961.66647859,  1015.14474028,
        1552.62143226,  1952.41318133, -1333.63585571,  2322.79691838,
        1836.90001537,  1304.09061058,  2953.41445576,   492.98393191,
        1767.37669644,  1538.49183718,  2763.22172385,   701.12148842,
        1497.83978767,  3171.20912649,  2739.98102691,  3083.23082208,
        1509.73099485,  -403.75963266,  3060.58311835,  1534.63240429,
        2126.56374336,  1430.22978634,  2213.95620759,  3036.4741329 ,
         764.02167445,  1388.09140204,  1465.81950004,  3230.24676147,
        4042.37691632,  1111.37396766,  -120.65093075,  1827.05333144,
        -849.31412397,  -890.7262893 ,  2360.67600989,  1911.94744736,
        1364.94730775,  2237.88769056,  3087.88358238,  2487.36446881,
        1814.98689195,  2108.9884168 ,  2583.22351327,  3355.50058083,
        4176.46701567,  1847.80429375,  -213.91397008,  2530.03065349,
        2693.79114486,  1780.5418679 ,  2397.73094511,  2878.72164823,
         645.15093239,  2048.6183123 ,  1608.21228578,  2769.52355705,
        1065.48183871,   918.44912311,  3766.67868122,  3814.66205357,
        1410.7289573 ,  2260.09921133,   498.28021713,  3261.6808007 ,
        5177.91724301,  1891.92363442,  2829.15601161,   773.54774305,
        4146.18105429,  2550.12978423,  1822.45400617,  5041.64196232,
        2290.32042249,  2780.82613652,  2520.30391402,  2414.57862285,
        2765.81690177,  2853.22395657,  2669.40595432,  3222.33271005,
        4130.07515115,  3661.38875333,  3939.25373924,   945.32092367,
        -808.14869278,  2457.45224456,  1321.18456948,  1952.22845759,
        3367.13993971,  1951.67051009,  2864.13125153,  1857.56201651,
        1020.88526106,   915.9956273 ,  3951.60057694,  2022.43194834,
         884.67257206,   829.67185432,  3743.02188251,  2831.09109906,
       -1102.98447805,  1292.80098363,   704.86366496,  3110.69668396,
        1545.47663428,  1703.52101085,  1635.1183242 ,  2935.0626438 ,
        1782.97957114,  2179.27190737,  3674.64951019,  2947.98082204,
         706.40521627,  2099.23593412,  1540.06424468,  1705.42749555,
        1370.95493115,  1122.58443429,  2892.92980769,  1587.8343426 ,
        2819.2737279 ,  3120.67250583,  3018.40641036,  3111.06793666,
        -212.61376002,  2813.27610394,   870.55690062,  2516.85695483,
         927.54919418,  1957.43247618,  1781.40939153,  1076.23761179,
        4352.1155469 ,  4301.33678227,  1097.0300905 ,   898.78417741,
         874.74704208,  3078.61542982,  4508.24882212,  1452.62111193,
       -1295.98616244,   925.8865704 ,   -22.29248101,  1925.49040522,
         837.71697559,  1780.04206868,  1776.06290589,  2395.20440265,
         647.64711295,  1757.15791235,  3054.93616635,  2669.03833584,
         992.60230748,  2976.49268873,  1562.16737413,  2163.73573806,
        3592.69690116,  5109.29133683,  3854.13657553,  3569.43067666,
       -1340.30350575,  1859.84378199,  2837.36028091,  2764.63713661,
        4760.77879185,  4124.68301835,  3866.51126571,   866.04248015,
        1836.15937883,  2340.600589  ,  2335.76036935,  1747.53581632,
        2439.00440635,  1404.84103149,  1541.48385505,  2564.61581654,
        2483.92482819,  2684.29194926,  3566.66566049, -1174.94915109,
         990.86447265,  1273.51914811,   980.63552801,  2412.07983221,
        3120.72919304,  2015.47928674,  2471.05997562,  4075.03277419,
        4061.07046273,  2254.05897456,  2588.39601088,  2395.03410064,
        4820.28161975,  2717.86602827,  1245.75155231,  1088.06789069,
        -442.22237808,  2827.2008785 ,  2623.7587844 ,  2321.4078903 ,
        3988.11070798,   880.95998178,  -914.07739568,  3428.93378694,
        5469.36611533,  1538.38988326,   857.62099014,  3053.72066158,
        1927.45787994,  1744.49174389,  1156.43668965,  1634.68559652,
        2435.77068346,  2936.64046258,  2849.9054158 ,  3744.95399279,
        1841.03746927,  4256.39758421,  1231.15947774,  1739.84089559,
        2071.02069356,   922.40883933,  -578.36411956,   378.99395213,
        3152.05265184,  2883.23419242,  2572.14931927,  3213.10506343,
        2040.01838969,   868.91833051,  1675.99720508,   802.97864181,
        2754.97435401,  4071.73665386,  4186.82510187,  2875.15818195,
        1203.14320104,  1210.50674476,  1508.07829506, -1129.98046159,
        2980.95564001,  2657.48328355,  2502.98642946,  2587.62864775,
        2564.01790552,  1686.12374433,  1392.80964227,  3187.97419853,
        1445.09637053,  1842.25112865,  2537.86297413,  -331.30843135,
        1953.5522925 ,   740.9689197 ,  4641.51188559,  2303.6677241 ,
        1950.86268172,  2696.22669036,   853.16295851,   -46.63099816,
         781.76137646,  1003.39883672,  3826.00532985,  1918.66779373,
         679.12829399,  1604.67414634,   -84.2086343 ,   643.76274734,
        3864.83839017,  2747.93817136,  2109.26181054,  1191.8502818 ,
         772.51223713,  3328.68861918,  3043.8582093 ,  3714.72209872,
        3047.81168371,  3960.8561282 ,  3417.25137571,  4623.96501229,
        4013.90762841,   791.07372971,  3004.77892755,   465.59659462,
        2333.27957981,   992.87508801,  2695.73256747,   -64.93938563,
        1708.31512122,  2611.11855753,  1703.05697411,  2321.29772397,
        3856.82919061,   164.36858438,  3958.69697663,  2035.27123517,
        1761.09641359,  1618.39971322,  2440.40915049,  3824.63229045,
        4398.80306604,  3820.5388695 ,  1801.78158237,  5053.0217696 ,
        1019.54437076,   996.49175235,  4477.08011317,  3648.03549775,
         376.72865829,  2451.95784691,  1311.34839899,  1187.57206307,
        3594.78466529,  3470.81911708,  2480.59756588,  3276.66573819,
        4525.38179375,  2824.8246832 ,  2570.81439788,  1537.80959923,
         567.2617457 ,  3103.0739986 ,  1930.40854786,  -115.67675269,
        1798.73370005,  2338.32927339,  3819.9758721 ,  2218.88086191,
        1072.29221001,  2571.06413847,   906.7756952 ,  2834.24444693,
        1558.19873057,  1576.25471337,  1712.73635068,  4047.78238028,
         733.43271891,  3871.58590265,  2408.88809734,  3090.36273107,
       -1253.33164848,  1861.53100996,  1952.85108484,  3061.54845475,
        2020.04643929,  2802.6207159 ,  1356.61337145,  1658.18389872,
        2993.57352372,  2796.48415346,  1035.96544801,  -165.23011237,
        4020.65592952,   570.6787162 ,  1280.88904878,  1782.83384501,
         987.84077602,   505.58799369,  4592.61766896,  1355.68909999,
        3149.94144054])

# 7. Evaluate the Outcome

In [140]:
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [155]:
print("\t\t\t\tTesting Dataset")
print('--------------------------------------------------------------------')
print('Mean Absolute Error : ',mean_absolute_error(Y_test,pred))
print('Mean squared Error : ',mean_squared_error(Y_test,pred)**(1/2))
print('R squared score  : ',r2_score(Y_test,pred))

				Testing Dataset
--------------------------------------------------------------------
Mean Absolute Error :  813.4254957177648
Mean squared Error :  1093.5899572821797
R squared score  :  0.5662898037791877

In [156]:
print("\t\t\t\tTraining Dataset")
print('--------------------------------------------------------------------')
print('Mean Absolute Error : ',mean_absolute_error(Y_train,LR.predict(X_train)))
print('Mean squared Error : ',mean_squared_error(Y_train,LR.predict(X_train))**(1/2))
print('R squared score  : ',r2_score(Y_train,LR.predict(X_train)))

				Training Dataset
--------------------------------------------------------------------
Mean Absolute Error :  838.5906658748696
Mean squared Error :  1131.1722195806055
R squared score  :  0.5631181370780571

Training = Testing -------------> Best fit            ----> Desired
Training > Testing -------------> Overfit             ----> Test performanced can be improved
Training < Testing -------------> Underfit / Worstfit ----> not required

In [157]:
Y_test.mean()

np.float64(2147.8192844079717)

In [158]:
838/2185*100

38.35240274599542

In [159]:
# 1.Regularization      
# 2. Regessian Algorithm

In [160]:
from sklearn.tree import DecisionTreeRegressor

In [161]:
DT=DecisionTreeRegressor()

In [162]:
DT.fit(X_train,Y_train)

DecisionTreeRegressor()

In [163]:
# predict Outcome
pred1=DT.predict(X_test)

In [164]:
mean_absolute_error(Y_test,pred1)

1070.9037854630715

In [165]:
mean_squared_error(Y_test,pred1)

2344303.269191509